### PR TITLE
On Windows do not change the compilation option to MT

### PR DESCRIPTION
**Pull request by traversaro**
All conda-forge libraries on Windows are compiled with the MD option, but bullet by default change that to MT, and this result in downstream linking errors such as:
~~~
2021-04-03T13:36:40.6871269Z BulletDynamics.lib(btRigidBody.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in DARTDoublePendulum.cc.obj
2021-04-03T13:36:40.6879189Z BulletCollision.lib(btCollisionObject.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in DARTDoublePendulum.cc.obj
2021-04-03T13:36:40.6880513Z BulletCollision.lib(btCollisionShape.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in DARTDoublePendulum.cc.obj
2021-04-03T13:36:40.6881567Z BulletCollision.lib(btConvexShape.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in DARTDoublePendulum.cc.obj
2021-04-03T13:36:40.6882739Z BulletCollision.lib(btDbvt.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in DARTDoublePendulum.cc.obj
2021-04-03T13:36:40.6883781Z BulletCollision.lib(btPolyhedralConvexShape.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in DARTDoublePendulum.cc.obj
2021-04-03T13:36:40.6885038Z BulletCollision.lib(btConvexPolyhedron.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in DARTDoublePendulum.cc.obj
2021-04-03T13:36:40.6886027Z LinearMath.lib(btConvexHull.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in DARTDoublePendulum.cc.obj
2021-04-03T13:36:40.6887059Z LinearMath.lib(btConvexHullComputer.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in DARTDoublePendulum.cc.obj
2021-04-03T13:36:40.6888094Z LinearMath.lib(btGeometryUtil.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in DARTDoublePendulum.cc.obj
~~~

Enabling the `USE_MSVC_RUNTIME_LIBRARY_DLL` CMake option ensure that Bullet uses the compilation flags used in the rest of conda-forge (see https://github.com/bulletphysics/bullet3/blob/db5be234dd2cc5471681663d04c9c3b247fc7e18/CMakeLists.txt#L100 ).

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by wolfv** [comment]
Thanks! I think we should move the previous build to broken

**Comment by traversaro** [comment]
> 
> 
> Thanks! I think we should move the previous build to broken

Ack, let's wait to see if this instead is actually working properly, otherwise we add in broken also this one.

**Comment by wolfv** [comment]
btw maybe we should also add bullet to the conda-forge pinnings?

**Comment by traversaro** [comment]
> 
> 
> > Thanks! I think we should move the previous build to broken
> 
> Ack, let's wait to see if this instead is actually working properly, otherwise we add in broken also this one.

Done https://github.com/conda-forge/admin-requests/pull/255 .

**Comment by traversaro** [comment]
> 
> 
> btw maybe we should also add bullet to the conda-forge pinnings?

Not sure, what is the policy w.r.t. to that? Ideally any package with run_exports should be listed in the conda-forge pinnings?

**Pull request merged**
