### PR TITLE
Update to 2.89

### PR DESCRIPTION
**Pull request by xantares**
@conda-forge-admin please rerender

### CODE REVIEW

**Comment by gonzalocasas** [comment]
Rather than disabling the examples, the build fail on macos can be fixed by using macos sdk 10.10 (instead of the default 10.9)

**Comment by gonzalocasas** [comment]
@xantares try adding a `conda_build_config.yaml` with:
```
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - 10.10                  # [osx]
```
otherwise, it's still defaulting to 10.09

**Comment by gonzalocasas** [comment]
@conda-forge-admin please rerender

**Comment by xantares** [comment]
@conda-forge-admin please rerender

**Pull request merged**
