### PR TITLE
Update recipe to rely on pypi as source of builds

### PR DESCRIPTION
**Pull request by gonzalocasas**
Update the recipe to the latest release of bullet/pybullet, and switch to base on pypi as source. Additionally, I propose myself to be co-maintainer to help keeping it up to date in the future.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gonzalocasas** [comment]
@conda-forge-admin, please rerender

**Comment by gonzalocasas** [comment]
@conda-forge-admin, please rerender

**Comment by gonzalocasas** [comment]
@conda-forge-admin, please rerender

**Comment by gonzalocasas** [comment]
@conda-forge-admin, please rerender

**Comment by gonzalocasas** [comment]
@xantares alright, from my side, this is ready to be merged if you agree. If you want to make any changes, please let me know.

**Comment by wolfv** [comment]
did you check that this also has the C++ libraries? I am not finding the .so files anymore... 

This should be a split package with `pybullet` and `bullet-cpp`. I don't think using pypi here is the right thing to do.

**Comment by gonzalocasas** [comment]
@wolfv I'll check the C++ side. I was under the impression than the pypi was building it as well, but it could be that not all artifacts end up in the right places. 

Regardless of this point: would you recommend to split anyway and create a `pybullet` package? or -if the C++ libraries part is resolved- this would be ok to keep as it is now?

**Comment by wolfv** [comment]
yes, we should have a package (`pybullet`) that depends on `bullet`, where `bullet` ships the C++ part, and pybullet the python bindings.

**Comment by gonzalocasas** [comment]
_continuing the conversation here_

> https://github.com/bulletphysics/bullet3/issues/3073#issuecomment-696756892
> I'll try to take care of this since this package is very important for my robotics work.

A quick option is to revert this PR entirely. However, the code & release situation of bullet/pybullet is so intermixed with each other, that I am unsure if it would not be better to have one package that installs both.

**Comment by gonzalocasas** [comment]
indeed, the C++ libs are not included:
image

@xantares @wolfv question: which way do we go: A) revert here, leave this package to be just the C++ part and create a second `pybullet` recipe for the `pybullet` part? or B) do we attempt to fix here and re-add the c++ libs?

**Comment by wolfv** [comment]
@gonzalocasas it's possible to define _multiple outputs_ for one recipe -- so this recipe could produce both: bullet & pybullet.

We might have to figure out the naming, though.

Ideally, current users of `bullet` would still get both (bullet + pybullet). We can make two additional sub-pacakges: cpp-bullet and pybullet.

**Comment by gonzalocasas** [comment]
@wolfv 👍 totally support the idea of keeping this package for multiple outputs (since it was already that before anyway), and then create two additional packages `bullet-cpp` and `pybullet` that would do only one or the other. This would prevent having to rename this package.

**Comment by wolfv** [comment]
cool! btw. I hit this issue when rebuilding ros-noetic today :) we're publishing ros-noetic and ros-melodic to the RoboStack conda channel now... and soon ROS foxy. If you're interested in this we can chat at gitter.im/RoboStack :)

**Comment by xantares** [comment]
I'd keep it simple: one single package providing everything, from the previous cmake scripts

**Comment by xantares** [comment]
@conda-forge/core is it possible to mark the 3.0.3 builds as broken ? these did not contain the library files and I decided to revert

**Comment by beckermr** [comment]
Please submit a PR to conda-forge/admin-requests

**Pull request merged**
