### PR TITLE
Add double precision library variants

### PR DESCRIPTION
**Pull request by johnwason**
This PR adds double precision float64 variants of the bullet libraries. It is based on the Debian patches, that create side-by-side 
versions of the libraries with a `-float64` postfix. It is based on the Debian patch, but takes a much simpler approach. Fixes https://github.com/johnwason/tesseract-robotics-superpack-feedstock/issues/5
 

Checklist
* [ x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by johnwason** [comment]
@wolfv @Tobias-Fischer @traversaro This PR is ready now. It fixes the Tesseract issue https://github.com/johnwason/tesseract-robotics-superpack-feedstock/issues/5 so we don't have to build Bullet in our packages.

**Comment by Tobias-Fischer** [comment]
Probably @traversaro is the best reviewer, he played recently with bullet double precision.

**Comment by traversaro** [comment]
I forgot to mention that perhaps an even simpler solution is to just build bullet-double packages, a bit like we did for libccd-double, if no one is interested in bullet-float packages.

**Comment by traversaro** [comment]
By the way, it seems that even Homebrew install bulled float and bullet double side-by-side: https://github.com/Homebrew/homebrew-core/blob/b1e78a203f1e7d8c19a21f700ce1b36629865176/Formula/bullet.rb#L39 .

**Comment by johnwason** [comment]
Can this be merged?

**Comment by Tobias-Fischer** [comment]
Same here. 

@wolfv are you happy to merge?

**Comment by wolfv** [comment]
Thanks!

**Pull request merged**
